name: PHP Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      # New step to validate the composer.json file before installing
      - name: Validate composer.json
        run: composer validate --strict

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      # Explicitly run the PHP Code Sniffer check
      - name: Run PHP Code Sniffer
        run: vendor/bin/phpcs --standard=PSR12 .

      - name: Run tests
        # Added --testdox for cleaner test output
        run: vendor/bin/phpunit --configuration phpunit.xml --testdox